In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/gemma/keras/gemma_instruct_2b_en/2/config.json
/kaggle/input/gemma/keras/gemma_instruct_2b_en/2/tokenizer.json
/kaggle/input/gemma/keras/gemma_instruct_2b_en/2/metadata.json
/kaggle/input/gemma/keras/gemma_instruct_2b_en/2/model.weights.h5
/kaggle/input/gemma/keras/gemma_instruct_2b_en/2/assets/tokenizer/vocabulary.spm
/kaggle/input/the-penal-code-1860/THE PENAL CODE 1860.pdf

In [2]:
import os
import requests

# Get PDF document path
pdf_path = "/kaggle/input/the-penal-code-1860/THE PENAL CODE 1860.pdf"

In [3]:
!pip install PyMuPDF
!pip install tqdm

Collecting PyMuPDF
  Downloading PyMuPDF-1.24.14-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.4 kB)
Downloading PyMuPDF-1.24.14-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (19.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 85.7 MB/s eta 0:00:00:00:0100:01
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.24.14
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (4.66.4)

In [4]:
import fitz #for opening document
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
   
    cleaned_text = text.replace("\n", " ").strip()
    return cleaned_text

def open_and_read_pdf(pdf_path: str) -> list[dict]:
   
    doc = fitz.open(pdf_path)
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):
        text = page.get_text()
        text = text_formatter(text=text)
        pages_and_texts.append({"page_number": page_number - 41, # adjusted page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(", ")),
                                "page_token_count": len(text) / 4, #1 token has approx 4 charactersz
                                "text": text})
    return pages_and_texts
pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 1967,
  'page_word_count': 503,
  'page_sentence_count_raw': 14,
  'page_token_count': 491.75,
  'text': '1 THE PENAL CODE, 1860    (ACT NO. XLV OF 1860).        [6th October, 1860]                             CHAPTER I    INTRODUCTION              Preamble     WHEREAS it is expedient to provide a general Penal Code for Bangladesh; It is  enacted as follows:-                         Title and extent of  operation of the  Code     1. This Act shall be called the 2[ Penal Code], and shall take effect throughout  Bangladesh.                         Punishment of  offences committed  within Bangladesh     2. Every person shall be liable to punishment under this Code and not otherwise for  every act or omission contrary to the provisions thereof, of which he shall be guilty  within Bangladesh.                         Punishment of  offences committed  beyond, but which  by law may be tried  within Bangladesh     3. Any person liable, by any Bangladesh Law, to be tried for an offence committed  beyond Bangladesh shall be dealt with according to the provisions of this Code for any  act committed beyond Bangladesh in the same manner as if such act had been  committed within Bangladesh.                         Extension of Code  to extra-territorial  offences     4. The provisions of this Code apply also to any offence committed by-    (1) any citizen of Bangladesh in any place without and beyond Bangladesh;    (2) [Omitted by Article 2 and Schedule of the Central Laws (Adaptation) Order, 1961.]    (3) [Omitted by section 3 and 2nd Schedule of the Bangladesh Laws (Revision And  Declaration) Act, 1973 (Act No. VIII of 1973).]    (4) any person on any ship or aircraft registered in Bangladesh wherever it may be.    Explanation.-In this section the word "offence" includes every act committed outside  Bangladesh which, if committed in Bangladesh, would be punishable under this Code.  Illustrations      (a) A, a Bangladesh subject, commits a murder in Uganda. He can be tried and  convicted of murder in any place in Bangladesh in which he may be found.'},
 {'page_number': -40,
  'page_char_count': 2697,
  'page_word_count': 647,
  'page_sentence_count_raw': 25,
  'page_token_count': 674.25,
  'text': '(b) B, a European British subject, commits a murder in 3[ Rangpur]. He can be tried  and convicted of murder in any place in Bangladesh in which he may be found.    (c) C, a foreigner who is in the service of the Bangladesh Government, commits a  murder in 4[ Khulna]. He can be tried and convicted of murder at any place in  Bangladesh in which he may be found.    (d) D, a British subject living in 5[ Khulna], instigates E to commit a murder in 6[  Chittagong]. D is guilty of abetting murder.                         Certain laws not to  be affected by this  Act     5. Nothing in this Act is intended to repeal, vary, suspend, or affect 7[ * * *] any of the  provisions of any Act for punishing mutiny and desertion of officers, soldiers, sailors or  airmen in the service of the 8[ Republic], or of any special or local law.                CHAPTER II    GENERAL EXPLANATIONS              Definitions in the  Code to be  understood subject  to exceptions     6. Throughout this Code every definition of an offence, every penal provision and every  illustration of every such definition or penal provision, shall be understood subject to  the exceptions contained in the chapter entitled "General Exceptions," though those  exceptions are not repeated in such definition, penal provision or illustration.  Illustrations      (a) The sections in this Code, which contain definitions of offences, do not express that  a child under seven years of age cannot commit such offences; but the definitions are  to be understood subject to the general exception which provides that nothing shall be  an offence which is done by a child under seven years of age.    (b) A, a police officer, without warrant, apprehends Z who has committed murder. Here  A is not guilty of the offence of wrongful confinement; for he was bound by law to  apprehend Z, and therefore the case falls within the general exception which provides  that "nothing is an offence which is done by a person who is bound by law to do it".                         Sense of expression  once explained     7. Every expression which is explained in any part of this Code is used in every part of  this Code in conformity with the explanation.                         Gender     8. The pronoun "he" and its derivatives are used of any person, whether male or  female.                     Number     9. Unless the contrary appears from the context, words importing the singular number  include the plural number, and words importing the plural number include the singular  number.                         “Man” “Woman”     10. The word “man” denotes a male human being of any age: the word “woman”  denotes a female human being of any age.'}]

In [5]:
import random

random.sample(pages_and_texts, k=2)

[{'page_number': -40,
  'page_char_count': 2697,
  'page_word_count': 647,
  'page_sentence_count_raw': 25,
  'page_token_count': 674.25,
  'text': '(b) B, a European British subject, commits a murder in 3[ Rangpur]. He can be tried  and convicted of murder in any place in Bangladesh in which he may be found.    (c) C, a foreigner who is in the service of the Bangladesh Government, commits a  murder in 4[ Khulna]. He can be tried and convicted of murder at any place in  Bangladesh in which he may be found.    (d) D, a British subject living in 5[ Khulna], instigates E to commit a murder in 6[  Chittagong]. D is guilty of abetting murder.                         Certain laws not to  be affected by this  Act     5. Nothing in this Act is intended to repeal, vary, suspend, or affect 7[ * * *] any of the  provisions of any Act for punishing mutiny and desertion of officers, soldiers, sailors or  airmen in the service of the 8[ Republic], or of any special or local law.                CHAPTER II    GENERAL EXPLANATIONS              Definitions in the  Code to be  understood subject  to exceptions     6. Throughout this Code every definition of an offence, every penal provision and every  illustration of every such definition or penal provision, shall be understood subject to  the exceptions contained in the chapter entitled "General Exceptions," though those  exceptions are not repeated in such definition, penal provision or illustration.  Illustrations      (a) The sections in this Code, which contain definitions of offences, do not express that  a child under seven years of age cannot commit such offences; but the definitions are  to be understood subject to the general exception which provides that nothing shall be  an offence which is done by a child under seven years of age.    (b) A, a police officer, without warrant, apprehends Z who has committed murder. Here  A is not guilty of the offence of wrongful confinement; for he was bound by law to  apprehend Z, and therefore the case falls within the general exception which provides  that "nothing is an offence which is done by a person who is bound by law to do it".                         Sense of expression  once explained     7. Every expression which is explained in any part of this Code is used in every part of  this Code in conformity with the explanation.                         Gender     8. The pronoun "he" and its derivatives are used of any person, whether male or  female.                     Number     9. Unless the contrary appears from the context, words importing the singular number  include the plural number, and words importing the plural number include the singular  number.                         “Man” “Woman”     10. The word “man” denotes a male human being of any age: the word “woman”  denotes a female human being of any age.'},
 {'page_number': -30,
  'page_char_count': 2884,
  'page_word_count': 599,
  'page_sentence_count_raw': 46,
  'page_token_count': 721.0,
  'text': 'suppressing riot, etc  attempts to use criminal force to such public servant, shall be punished with  imprisonment of either description for a term which may extend to three years or with  fine, or with both.                         Wantonly giving  provocation with  intent to cause riot-  if rioting be  committed; if not  committed     153. Whoever malignantly, or wantonly, by doing anything which is illegal, gives  provocation to any person intending or knowing it to be likely that such provocation will  cause the offence of rioting to be committed, shall, if the offence of rioting be committed  in consequence of such provocation, be punished with imprisonment of either  description for a term which may extend to one year, or with fine, or with both; and if the  offence of rioting be not committed, with imprisonment of either description for a term  which may extend to six months, or with fine, or with both.                         Promoting enmity  between classes     63[ 153A. Whoever by words, either spoken or written, or by signs, or by visible  representations, or otherwise, promotes or attempts to promote feelings of enmity or  hatred between different classes of the citizens of Bangladesh, shall be punished with  imprisonment which may extend to two years, or with fine, or with both.]    Explanation.-It does not amount to an offence within the meaning of this section to  point out, without malicious intention and with an honest view to their removal, matters  which are producing or have a tendency to produce, feelings of enmity or hatred  between different classes of the citizens of Bangladesh.                         Inducing students,  etc to take part in  political activity     64[ 153B. Whoever by words, either spoken or written, or by signs, or by visible  representations, or otherwise, induce or attempts to induce any student, or any class of  students, or any institution interested in or connected with students, to take part in any  political activity which disturbs or undermines, or is likely to disturb or undermine, the  public order shall be punished with imprisonment which may extend to two years or with  fine, or with both.]        Punishment for  committing affray     160. Whoever commits an affray, shall be punished with imprisonment of either  description for a term which may extend to one month, or with fine which may extend to  one hundred taka, or with both.    CHAPTER IXA    OF OFFENCES RELATING TO ELECTIONS    Punishment of  bribery     171E. Whoever commits the offence of bribery shall be punished with imprisonment of  either description for a term which may extend to one year, or with fine, or with both:    Provided that bribery by treating shall be punished with fine only.    Explanation.-Treating means that form of bribery where the gratification consists in food,  drink, entertainment, or provision.'}]

### Get some stats on the text

Let's perform a rough exploratory data analysis (EDA) to get an idea of the size of the texts (e.g. character counts, word counts etc) we're working with.

In [6]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,1967,503,14,491.75,"1 THE PENAL CODE, 1860 (ACT NO. XLV OF 1860..."
1,-40,2697,647,25,674.25,"(b) B, a European British subject, commits a m..."
2,-39,2150,575,25,537.50,“Person” 11. The word “person” includes an...
3,-38,3007,594,51,751.75,"“Court of justice” 20. The words ""Court of..."
4,-37,2533,618,16,633.25,A Municipal Commissioner is a public servant. ...

In [7]:
df.tail()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
16,-25,3361,766,56,840.25,or drink intended for sale noxious as food o...
17,-24,2968,629,59,742.00,"has in his possession any obscene book, pamphl..."
18,-23,3496,750,55,874.00,"Offering of prize in connection with trade, ..."
19,-22,3184,698,31,796.00,Of Criminal Force and Assault Punishment fo...
20,-21,958,191,16,239.50,Assault or criminal force on grave provocati...

In [8]:
df.shape

(21, 6)

In [9]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,21.0,21.00,21.00,21.00,21.00
mean,-31.0,2818.05,640.76,38.24,704.51
std,6.2,610.33,126.45,15.41,152.58
min,-41.0,958.00,191.00,14.00,239.50
25%,-36.0,2609.00,599.00,25.00,652.25
50%,-31.0,2968.00,683.00,41.00,742.00
75%,-26.0,3204.00,711.00,51.00,801.00
max,-21.0,3572.00,766.00,62.00,893.00

### Further text processing (splitting pages into sentences)
We will to follow the workflow of:

`Ingest text -> split it into groups/chunks -> embed the groups/chunks -> use the embeddings`

Why split into sentences?

* Easier to handle than larger pages of text (especially if pages are densely filled with text).
* Can get specific and find out which group of sentences were used to help within a RAG pipeline.


We will use spaCy to break our text into sentences since it's likely a bit more robust than just using `text.split(". ")`.

In [10]:
from spacy.lang.en import English

nlp = English()

nlp.add_pipe("sentencizer")

for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]
    
    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/21 [00:00<?, ?it/s]

In [11]:
random.sample(pages_and_texts, k=1)

[{'page_number': -34,
  'page_char_count': 3157,
  'page_word_count': 703,
  'page_sentence_count_raw': 62,
  'page_token_count': 789.25,
  'text': 'offence  singly or jointly with any other person, commits that offence.  Illustrations      (a) A and B agree to murder Z by severally and at different times giving him small  doses of poison. A and B administer the poison according to the agreement with intent  to murder Z. Z dies from the effects of the several doses of poison so administered to  him. Here A and B intentionally co-operate in the commission of murder and as each of  them does an act by which the death is caused, they are both guilty of the offence  though their acts are separate.    (b) A and B are joint jailors, and as such, have the charge of Z, a prisoner, alternately  for six hours at a time. A and B, intending to cause Z\'s death, knowingly co-operate in  causing that effect by illegally omitting, each during the time of his attendance, to  furnish Z with food supplied to them for that purpose. Z dies of hunger. Both A and B  are guilty of the murder of Z.    (c) A, a jailor, has the charge of Z, a prisoner. A intending to cause Z\'s death, illegally  omits to supply Z with food; in consequence of which Z is much reduced in strength,  but the starvation is not sufficient to cause his death. A is dismissed from his office,  and B succeeds him. B, without collusion or co-operation with A, illegally omits to  supply Z with food, knowing that he is likely thereby to cause Z\'s death. Z dies of  hunger. B is guilty of murder, but, as A did not co-operate with B, A is guilty only of an  attempt to commit murder.                         Persons concerned  in criminal act may  be guilty of different  offences     38. Where several persons are engaged or concerned in the commission of a criminal  act, they may be guilty of different offences by means of that act.    Illustration    A attacks Z under such circumstances of grave provocation that his killing of Z would  be only culpable homicide not amounting to murder. B having ill-will towards Z and  intending to kill him, and not having been subject to the provocation, assists A in killing  Z. Here, though A and B are both engaged in causing Z\'s death, B is guilty of murder,  and A is guilty only of culpable homicide.                         “Voluntarily”     39. A person is said to cause an effect "voluntarily" when he causes it by means  whereby he intended to cause it, or by means which, at the time of employing those  means, he knew or had reason to believe to be likely to cause it.    Illustration    A sets fire, by night, to an inhabited house in a large town, for the purpose of  facilitating robbery and thus causes the death of a person. Here, A may not have  intended to cause death, and may even be sorry that death has been caused by his  act: yet, if he knew that he was likely to cause death, he has caused death voluntarily.                         “Offence”     40. Except in the chapters and sections mentioned in clauses 2 and 3 of this section,  the word "offence" denotes a thing made punishable by this Code.    In Chapter IV, Chapter VA and in the following sections, namely, sections 64, 65, 66,  67, 71, 109, 110, 112, 114, 115, 116, 117, 187, 194, 195, 203, 211, 213, 214, 221,',
  'sentences': ['offence  singly or jointly with any other person, commits that offence.',
   ' Illustrations      (a) A and B agree to murder Z by severally and at different times giving him small  doses of poison.',
   'A and B administer the poison according to the agreement with intent  to murder Z. Z dies from the effects of the several doses of poison so administered to  him.',
   'Here A and B intentionally co-operate in the commission of murder and as each of  them does an act by which the death is caused, they are both guilty of the offence  though their acts are separate.',
   '   (b) A and B are joint jailors, and as such, have the charge of Z, a prisoner, alternately  for six hours at a time.',
   "A and B, intending to cause Z's death, knowingly co-operate in  causing that effect by illegally omitting, each during the time of his attendance, to  furnish Z with food supplied to them for that purpose.",
   'Z dies of hunger.',
   'Both A and B  are guilty of the murder of Z.    (c) A, a jailor, has the charge of Z, a prisoner.',
   "A intending to cause Z's death, illegally  omits to supply Z with food; in consequence of which Z is much reduced in strength,  but the starvation is not sufficient to cause his death.",
   'A is dismissed from his office,  and B succeeds him.',
   "B, without collusion or co-operation with A, illegally omits to  supply Z with food, knowing that he is likely thereby to cause Z's death.",
   'Z dies of  hunger.',
   'B is guilty of murder, but, as A did not co-operate with B, A is guilty only of an  attempt to commit murder.',
   '                        Persons concerned  in criminal act may  be guilty of different  offences     38.',
   'Where several persons are engaged or concerned in the commission of a criminal  act, they may be guilty of different offences by means of that act.',
   '   Illustration    A attacks Z under such circumstances of grave provocation that his killing of Z would  be only culpable homicide not amounting to murder.',
   "B having ill-will towards Z and  intending to kill him, and not having been subject to the provocation, assists A in killing  Z. Here, though A and B are both engaged in causing Z's death, B is guilty of murder,  and A is guilty only of culpable homicide.",
   '                        “Voluntarily”     39.',
   'A person is said to cause an effect "voluntarily" when he causes it by means  whereby he intended to cause it, or by means which, at the time of employing those  means, he knew or had reason to believe to be likely to cause it.',
   '   Illustration    A sets fire, by night, to an inhabited house in a large town, for the purpose of  facilitating robbery and thus causes the death of a person.',
   'Here, A may not have  intended to cause death, and may even be sorry that death has been caused by his  act: yet, if he knew that he was likely to cause death, he has caused death voluntarily.',
   '                        “Offence”     40.',
   'Except in the chapters and sections mentioned in clauses 2 and 3 of this section,  the word "offence" denotes a thing made punishable by this Code.',
   '   In Chapter IV, Chapter VA and in the following sections, namely, sections 64, 65, 66,  67, 71, 109, 110, 112, 114, 115, 116, 117, 187, 194, 195, 203, 211, 213, 214, 221,'],
  'page_sentence_count_spacy': 24}]

In [12]:
df = pd.DataFrame(pages_and_texts)
df

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text,sentences,page_sentence_count_spacy
0,-41,1967,503,14,491.75,"1 THE PENAL CODE, 1860 (ACT NO. XLV OF 1860...","[1 THE PENAL CODE, 1860 (ACT NO., XLV OF 18...",16
1,-40,2697,647,25,674.25,"(b) B, a European British subject, commits a m...","[(b) B, a European British subject, commits a ...",21
2,-39,2150,575,25,537.50,“Person” 11. The word “person” includes an...,"[“Person” 11., The word “person” includes ...",22
3,-38,3007,594,51,751.75,"“Court of justice” 20. The words ""Court of...","[“Court of justice” 20., The words ""Court ...",7
4,-37,2533,618,16,633.25,A Municipal Commissioner is a public servant. ...,[A Municipal Commissioner is a public servant....,18
5,-36,2625,556,33,656.25,"Property in possession of wife, clerk or ser...","[Property in possession of wife, clerk or se...",19
6,-35,2609,683,25,652.25,the signature. “Valuab...,"[the signature., “Valu...",20
7,-34,3157,703,62,789.25,offence singly or jointly with any other pers...,[offence singly or jointly with any other per...,24
8,-33,2373,691,32,593.25,"222, 223, 224, 225, 327, 328, 329, 330, 331, 3...","[222, 223, 224, 225, 327, 328, 329, 330, 331, ...",24
9,-32,2636,606,42,659.00,“Good faith” 52. Nothing is said to be don...,"[“Good faith” 52., Nothing is said to be d...",13
10,-31,3240,761,47,810.00,"Joining or continuing in unlawful assembly, ...","[Joining or continuing in unlawful assembly,...",17
11,-30,2884,599,46,721.00,"suppressing riot, etc attempts to use crimina...","[suppressing riot, etc attempts to use crimin...",10
12,-29,3204,711,23,801.00,Punishment for undue influence or personatio...,[Punishment for undue influence or personati...,10
13,-28,3572,733,51,893.00,"servant by such bidding, shall be punished wi...","[servant by such bidding, shall be punished w...",14
14,-27,3392,695,53,848.00,CHAPTER XI OF FALSE EVIDENCE AND OFFENCES A...,[CHAPTER XI OF FALSE EVIDENCE AND OFFENCES ...,4
15,-26,3166,747,41,791.50,CHAPTER XIII OF OFFENCES RELATING TO WEIGHT...,[CHAPTER XIII OF OFFENCES RELATING TO WEIGH...,16
16,-25,3361,766,56,840.25,or drink intended for sale noxious as food o...,[or drink intended for sale noxious as food ...,15
17,-24,2968,629,59,742.00,"has in his possession any obscene book, pamphl...","[has in his possession any obscene book, pamph...",8
18,-23,3496,750,55,874.00,"Offering of prize in connection with trade, ...","[Offering of prize in connection with trade,...",10
19,-22,3184,698,31,796.00,Of Criminal Force and Assault Punishment fo...,[Of Criminal Force and Assault Punishment f...,14
20,-21,958,191,16,239.50,Assault or criminal force on grave provocati...,[Assault or criminal force on grave provocat...,5

In [13]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,21.0,21.00,21.00,21.00,21.00,21.00
mean,-31.0,2818.05,640.76,38.24,704.51,14.62
std,6.2,610.33,126.45,15.41,152.58,5.98
min,-41.0,958.00,191.00,14.00,239.50,4.00
25%,-36.0,2609.00,599.00,25.00,652.25,10.00
50%,-31.0,2968.00,683.00,41.00,742.00,15.00
75%,-26.0,3204.00,711.00,51.00,801.00,19.00
max,-21.0,3572.00,766.00,62.00,893.00,24.00

### Chunking our sentences together
Why do we do this?

1. Easier to manage similar sized chunks of text.
2. Don't overload the embedding models capacity for tokens (e.g. if an embedding model has a capacity of 384 tokens, there could be information loss if you try to embed a sequence of 400+ tokens).
3. Our LLM context window (the amount of tokens an LLM can take in) may be limited and requires compute power so we want to make sure we're using it as well as possible.

In [14]:
chunk_size = 10
def split_list(input_list: list[str], 
               slice_size: int=chunk_size) -> list[list[str]]:

    return [input_list[i:i+slice_size] for i in range(0, len(input_list), slice_size)]

for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])

  0%|          | 0/21 [00:00<?, ?it/s]

In [15]:
random.sample(pages_and_texts,k=1)

[{'page_number': -28,
  'page_char_count': 3572,
  'page_word_count': 733,
  'page_sentence_count_raw': 51,
  'page_token_count': 893.0,
  'text': 'servant  by such bidding, shall be punished with imprisonment of either description for a term which  may extend to one month, or with fine which may extend to two hundred taka, or with both.                       Obstructing public  servant in  discharge of  public functions     186. Whoever voluntarily obstructs any public servant in the discharge of his public functions,  shall be punished with imprisonment of either description for a term which may extend to  three months, or with fine which may extend to five hundred taka, or with both.                       Omission to assist  public servant  when bound by  law to give  assistance     187. Whoever, being bound by law to render or furnish assistance to any public servant in  the execution of his public duty, intentionally omits to give such assistance, shall be punished  with simple imprisonment for a term which may extend to one month, or with fine which may  extend to two hundred taka, or with both;    and if such assistance be demanded of him by a public servant legally competent to make  such demand for the purposes of executing any process lawfully issued by a Court of Justice,  or of preventing the commission of an offence, or of suppressing a riot, or affray, or of  apprehending a person charged with or guilty of an offence, or of having escaped from lawful  custody, shall be punished with simple imprisonment for a term which may extend to six  months, or with fine which may extend to five hundred taka, or with both.                       Disobedience to  order duly  promulgated by  public servant     188. Whoever, knowing that, by an order promulgated by a public servant lawfully  empowered to promulgate such order, he is directed to abstain from a certain act, or to take  certain order with certain property in his possession or under his management, disobeys  such direction,    shall, if such disobedience causes or tends to cause obstruction, annoyance or injury, or risk  of obstruction, annoyance or injury, to any persons lawfully employed, be punished with  simple imprisonment for a term which may extend to one month or with fine which may  extend to two hundred taka, or with both;    and if such disobedience causes or tends to cause danger to human life, health or safety, or  causes or tends to cause a riot or affray, shall be punished with imprisonment of either  description for a term which may extend to six months, or with fine which may extend to one  thousand taka, or with both.    Explanation.-It is not necessary that the offender should intend to produce harm, or  contemplate his disobedience as likely to produce harm. It is sufficient that he knows of the  order which he disobeys, and that his disobedience produces, or is likely to produce, harm.    Illustration    An order is promulgated by a public servant lawfully empowered to promulgate such order,  directing that a religious procession shall not pass down a certain street. A knowingly  disobeys the order, and thereby causes danger of riot. A has committed the offence defined  in this section.    Threat of injury to  public servant     189. Whoever holds out any threat of injury to any public servant, or to any person in  whom he believes that public servant to be interested, for the purpose of inducing that  public servant to do any act, or to forbear or delay to do any act, connected with the  exercise of the public functions of such public servant, shall be punished with  imprisonment of either description for a term which may extend to two years, or with fine,  or with both.',
  'sentences': ['servant  by such bidding, shall be punished with imprisonment of either description for a term which  may extend to one month, or with fine which may extend to two hundred taka, or with both.',
   '                      Obstructing public  servant in  discharge of  public functions     186.',
   'Whoever voluntarily obstructs any public servant in the discharge of his public functions,  shall be punished with imprisonment of either description for a term which may extend to  three months, or with fine which may extend to five hundred taka, or with both.',
   '                      Omission to assist  public servant  when bound by  law to give  assistance     187.',
   'Whoever, being bound by law to render or furnish assistance to any public servant in  the execution of his public duty, intentionally omits to give such assistance, shall be punished  with simple imprisonment for a term which may extend to one month, or with fine which may  extend to two hundred taka, or with both;    and if such assistance be demanded of him by a public servant legally competent to make  such demand for the purposes of executing any process lawfully issued by a Court of Justice,  or of preventing the commission of an offence, or of suppressing a riot, or affray, or of  apprehending a person charged with or guilty of an offence, or of having escaped from lawful  custody, shall be punished with simple imprisonment for a term which may extend to six  months, or with fine which may extend to five hundred taka, or with both.',
   '                      Disobedience to  order duly  promulgated by  public servant     188.',
   'Whoever, knowing that, by an order promulgated by a public servant lawfully  empowered to promulgate such order, he is directed to abstain from a certain act, or to take  certain order with certain property in his possession or under his management, disobeys  such direction,    shall, if such disobedience causes or tends to cause obstruction, annoyance or injury, or risk  of obstruction, annoyance or injury, to any persons lawfully employed, be punished with  simple imprisonment for a term which may extend to one month or with fine which may  extend to two hundred taka, or with both;    and if such disobedience causes or tends to cause danger to human life, health or safety, or  causes or tends to cause a riot or affray, shall be punished with imprisonment of either  description for a term which may extend to six months, or with fine which may extend to one  thousand taka, or with both.',
   '   Explanation.-It is not necessary that the offender should intend to produce harm, or  contemplate his disobedience as likely to produce harm.',
   'It is sufficient that he knows of the  order which he disobeys, and that his disobedience produces, or is likely to produce, harm.',
   '   Illustration    An order is promulgated by a public servant lawfully empowered to promulgate such order,  directing that a religious procession shall not pass down a certain street.',
   'A knowingly  disobeys the order, and thereby causes danger of riot.',
   'A has committed the offence defined  in this section.',
   '   Threat of injury to  public servant     189.',
   'Whoever holds out any threat of injury to any public servant, or to any person in  whom he believes that public servant to be interested, for the purpose of inducing that  public servant to do any act, or to forbear or delay to do any act, connected with the  exercise of the public functions of such public servant, shall be punished with  imprisonment of either description for a term which may extend to two years, or with fine,  or with both.'],
  'page_sentence_count_spacy': 14,
  'sentence_chunks': [['servant  by such bidding, shall be punished with imprisonment of either description for a term which  may extend to one month, or with fine which may extend to two hundred taka, or with both.',
    '                      Obstructing public  servant in  discharge of  public functions     186.',
    'Whoever voluntarily obstructs any public servant in the discharge of his public functions,  shall be punished with imprisonment of either description for a term which may extend to  three months, or with fine which may extend to five hundred taka, or with both.',
    '                      Omission to assist  public servant  when bound by  law to give  assistance     187.',
    'Whoever, being bound by law to render or furnish assistance to any public servant in  the execution of his public duty, intentionally omits to give such assistance, shall be punished  with simple imprisonment for a term which may extend to one month, or with fine which may  extend to two hundred taka, or with both;    and if such assistance be demanded of him by a public servant legally competent to make  such demand for the purposes of executing any process lawfully issued by a Court of Justice,  or of preventing the commission of an offence, or of suppressing a riot, or affray, or of  apprehending a person charged with or guilty of an offence, or of having escaped from lawful  custody, shall be punished with simple imprisonment for a term which may extend to six  months, or with fine which may extend to five hundred taka, or with both.',
    '                      Disobedience to  order duly  promulgated by  public servant     188.',
    'Whoever, knowing that, by an order promulgated by a public servant lawfully  empowered to promulgate such order, he is directed to abstain from a certain act, or to take  certain order with certain property in his possession or under his management, disobeys  such direction,    shall, if such disobedience causes or tends to cause obstruction, annoyance or injury, or risk  of obstruction, annoyance or injury, to any persons lawfully employed, be punished with  simple imprisonment for a term which may extend to one month or with fine which may  extend to two hundred taka, or with both;    and if such disobedience causes or tends to cause danger to human life, health or safety, or  causes or tends to cause a riot or affray, shall be punished with imprisonment of either  description for a term which may extend to six months, or with fine which may extend to one  thousand taka, or with both.',
    '   Explanation.-It is not necessary that the offender should intend to produce harm, or  contemplate his disobedience as likely to produce harm.',
    'It is sufficient that he knows of the  order which he disobeys, and that his disobedience produces, or is likely to produce, harm.',
    '   Illustration    An order is promulgated by a public servant lawfully empowered to promulgate such order,  directing that a religious procession shall not pass down a certain street.'],
   ['A knowingly  disobeys the order, and thereby causes danger of riot.',
    'A has committed the offence defined  in this section.',
    '   Threat of injury to  public servant     189.',
    'Whoever holds out any threat of injury to any public servant, or to any person in  whom he believes that public servant to be interested, for the purpose of inducing that  public servant to do any act, or to forbear or delay to do any act, connected with the  exercise of the public functions of such public servant, shall be punished with  imprisonment of either description for a term which may extend to two years, or with fine,  or with both.']],
  'num_chunks': 2}]

In [16]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,21.0,21.00,21.00,21.00,21.00,21.00,21.00
mean,-31.0,2818.05,640.76,38.24,704.51,14.62,1.86
std,6.2,610.33,126.45,15.41,152.58,5.98,0.73
min,-41.0,958.00,191.00,14.00,239.50,4.00,1.00
25%,-36.0,2609.00,599.00,25.00,652.25,10.00,1.00
50%,-31.0,2968.00,683.00,41.00,742.00,15.00,2.00
75%,-26.0,3204.00,711.00,51.00,801.00,19.00,2.00
max,-21.0,3572.00,766.00,62.00,893.00,24.00,3.00

### Splitting each chunk into its own item

In [17]:
import re

pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]
        
        # Join the sentences together into a paragraph-like structure, aka a chunk (so they are a single string)
        joined_sentence_chunk = "".join(sentence_chunk).replace("  "," ").strip()
        joined_sentence_chunk = re.sub(r'\.(A-Z)', r'. \1', joined_sentence_chunk) # convert ".A"to ". A"(only for capital letter)
        chunk_dict["sentence_chunk"] = joined_sentence_chunk
        
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4
        
        pages_and_chunks.append(chunk_dict)
    
len(pages_and_chunks)

  0%|          | 0/21 [00:00<?, ?it/s]

39

In [18]:
random.sample(pages_and_chunks, k=1)

[{'page_number': -26,
  'sentence_chunk': 'Malignant act likely to spread infection of disease dangerous to life   270.Whoever malignantly does any act which is, and which he knows or has reason to believe to be, likely to spread the infection of any disease dangerous to life, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.            Disobedience to quarantine rule   271.Whoever knowingly disobeys any rule made and promulgated by the Government for putting any vessel into a state of quarantine, or for regulating the intercourse of vessels in a state of quarantine with the shore or with other vessels, or for regulating the intercourse between places where an infectious disease prevails and other places, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine, or with both.            Adulteration of food  272.Whoever adulterates any article of food or drink, so as to make such article',
  'chunk_char_count': 992,
  'chunk_word_count': 188,
  'chunk_token_count': 248.0}]

In [19]:
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count        39.00             39.00             39.00              39.00
mean        -32.21           1449.28            277.36             362.32
std           5.98            917.48            166.81             229.37
min         -41.00            111.00             22.00              27.75
25%         -37.00            743.50            148.00             185.88
50%         -33.00           1204.00            240.00             301.00
75%         -27.50           1998.00            390.50             499.50
max         -21.00           3366.00            620.00             841.50

In [20]:
 df.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count
0,-41,"1 THE PENAL CODE, 1860 (ACT NO.XLV OF 1860). ...",1289,279,322.25
1,-41,(3) [Omitted by section 3 and 2nd Schedule of ...,545,92,136.25
2,-40,"(b) B, a European British subject, commits a m...",1251,240,312.75
3,-40,"Illustrations (a) The sections in this Code,...",1196,248,299.00
4,-40,The word “man” denotes a male human being of a...,111,22,27.75

In [22]:
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count : {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

ValueError: Cannot take a larger sample than population when 'replace=False'

In [23]:
#filtering rows with token under 30
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -41,
  'sentence_chunk': '1 THE PENAL CODE, 1860  (ACT NO.XLV OF 1860).    [6th October, 1860]               CHAPTER I  INTRODUCTION       Preamble   WHEREAS it is expedient to provide a general Penal Code for Bangladesh; It is enacted as follows:-             Title and extent of operation of the Code   1.This Act shall be called the 2[ Penal Code], and shall take effect throughout Bangladesh.            Punishment of offences committed within Bangladesh   2.Every person shall be liable to punishment under this Code and not otherwise for every act or omission contrary to the provisions thereof, of which he shall be guilty within Bangladesh.            Punishment of offences committed beyond, but which by law may be tried within Bangladesh   3.Any person liable, by any Bangladesh Law, to be tried for an offence committed beyond Bangladesh shall be dealt with according to the provisions of this Code for any act committed beyond Bangladesh in the same manner as if such act had been committed within Bangladesh.            Extension of Code to extra-territorial offences   4.The provisions of this Code apply also to any offence committed by-  (1) any citizen of Bangladesh in any place without and beyond Bangladesh;  (2) [Omitted by Article 2 and Schedule of the Central Laws (Adaptation) Order, 1961.]',
  'chunk_char_count': 1289,
  'chunk_word_count': 279,
  'chunk_token_count': 322.25},
 {'page_number': -41,
  'sentence_chunk': '(3) [Omitted by section 3 and 2nd Schedule of the Bangladesh Laws (Revision And Declaration) Act, 1973 (Act No.VIII of 1973).]  (4) any person on any ship or aircraft registered in Bangladesh wherever it may be.  Explanation.-In this section the word "offence" includes every act committed outside Bangladesh which, if committed in Bangladesh, would be punishable under this Code. Illustrations   (a) A, a Bangladesh subject, commits a murder in Uganda.He can be tried and convicted of murder in any place in Bangladesh in which he may be found.',
  'chunk_char_count': 545,
  'chunk_word_count': 92,
  'chunk_token_count': 136.25}]

In [24]:
random.sample(pages_and_chunks_over_min_token_len, k=1)

[{'page_number': -41,
  'sentence_chunk': '1 THE PENAL CODE, 1860  (ACT NO.XLV OF 1860).    [6th October, 1860]               CHAPTER I  INTRODUCTION       Preamble   WHEREAS it is expedient to provide a general Penal Code for Bangladesh; It is enacted as follows:-             Title and extent of operation of the Code   1.This Act shall be called the 2[ Penal Code], and shall take effect throughout Bangladesh.            Punishment of offences committed within Bangladesh   2.Every person shall be liable to punishment under this Code and not otherwise for every act or omission contrary to the provisions thereof, of which he shall be guilty within Bangladesh.            Punishment of offences committed beyond, but which by law may be tried within Bangladesh   3.Any person liable, by any Bangladesh Law, to be tried for an offence committed beyond Bangladesh shall be dealt with according to the provisions of this Code for any act committed beyond Bangladesh in the same manner as if such act had been committed within Bangladesh.            Extension of Code to extra-territorial offences   4.The provisions of this Code apply also to any offence committed by-  (1) any citizen of Bangladesh in any place without and beyond Bangladesh;  (2) [Omitted by Article 2 and Schedule of the Central Laws (Adaptation) Order, 1961.]',
  'chunk_char_count': 1289,
  'chunk_word_count': 279,
  'chunk_token_count': 322.25}]

### Embedding our text chunks

Embeddings of text will mean that similar meaning texts have similar numerical representation.


Our goal is to turn each of our chunks into a numerical representation (an embedding vector, where a vector is a sequence of numbers arranged in order).

We'll use our computers to find patterns in the embeddings and then we can use their text mappings to further our understanding.

We'll use the [`sentence-transformers`](https://www.sbert.net/docs/installation.html) library which contains many pre-trained embedding models.

Specifically, we'll get the `all-mpnet-base-v2` model (you can see the model's intended use on the [Hugging Face model card](https://huggingface.co/sentence-transformers/all-mpnet-base-v2#intended-uses)).

In [25]:
!pip install sentence-transformers # for embedding models

Collecting sentence-transformers
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.45.1)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (2.4.0)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.14.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (0.25.1)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (10.3.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.15.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.5.15)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.20.0)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.9->huggingface-hub>=0.20.0->sentence-transformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 11.2 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.3.1

In [26]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device="cuda")


for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

  0%|          | 0/38 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [27]:
pages_and_chunks_over_min_token_len[0]["embedding"].shape

(768,)

Our embedding has a shape of `(768,)` meaning it's a vector of 768 numbers which represent our text in high-dimensional space.

In [28]:
# Turn text chunks into a single list
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]
text_chunks[9]

'Losing wrongfully   A person is said to gain wrongfully when such person retains wrongfully, as well as when such person acquires wrongfully.A person is said to loss wrongfully when such person is wrongfully kept out of any property, as well as when such person is wrongfully deprived of property.            “Dishonestly”   24.Whoever does anything with the intention of causing wrongful gain to one person or wrongful loss to another person, is said to do that thing "dishonestly".            “Fraudulently"   25.A person is said to do a thing fraudulently if he does that thing with intent to defraud but not otherwise.            “Reason to believe”  26.A person is said to have "reason to believe" a thing if he has sufficient cause to believe that thing but not otherwise.'

In [29]:
len(text_chunks)

38

In [30]:
text_chunk_embeddings = embedding_model.encode(text_chunks,
                                               batch_size=16, # Embed all texts in batches
                                               convert_to_tensor=True)
text_chunk_embeddings[0]

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

tensor([ 4.0765e-02, -6.9201e-02,  2.3881e-02, -5.3142e-02, -4.3559e-02,
         4.9251e-02,  2.5954e-02,  2.1812e-02,  5.9380e-02,  4.0764e-02,
         3.2882e-03, -3.7364e-02,  1.4155e-02,  1.2345e-02,  6.3931e-02,
         4.1709e-02,  4.5600e-03,  5.8557e-03,  5.7257e-03,  2.6336e-02,
         1.8689e-02,  1.7316e-02,  7.4427e-03,  5.4950e-03,  3.2433e-02,
         2.4070e-02,  4.5923e-03,  1.2356e-02, -5.4996e-02, -1.1292e-02,
         5.2693e-02,  2.2630e-02,  4.0594e-02, -1.7483e-02,  1.6937e-06,
        -2.6182e-02, -1.7500e-02, -3.9062e-02, -4.1819e-02,  3.6031e-02,
        -3.9795e-02, -3.1730e-04,  1.1715e-02, -1.5238e-02, -3.9628e-02,
        -4.7980e-02,  1.1799e-02,  6.3447e-02,  9.3251e-03,  1.8541e-02,
         9.4109e-03, -8.3883e-02, -5.5643e-02, -4.0032e-02,  5.0022e-02,
         1.4523e-02, -7.0000e-03,  5.1976e-02,  4.4669e-02,  4.6007e-02,
         1.5093e-03, -1.6249e-02,  3.0002e-02, -2.5551e-02, -6.9359e-03,
        -7.3252e-02, -1.2194e-02,  9.0582e-03,  5.1183e-02,  2.4803e-02,
        -2.7556e-04, -3.3894e-02, -1.0963e-03,  2.1678e-02, -2.0236e-02,
        -7.5554e-02, -9.5138e-03,  5.2697e-02, -4.3774e-02,  3.2870e-02,
         6.8641e-02,  1.7756e-02, -4.5064e-02,  2.9822e-03,  7.4094e-03,
        -2.9872e-02, -4.2822e-02, -2.5813e-02, -7.9460e-02, -8.5719e-03,
        -2.2967e-02,  3.6743e-02,  2.5049e-02, -7.2794e-03, -1.0990e-02,
         1.7263e-02,  1.6866e-02, -4.8982e-02,  6.1891e-02, -2.8326e-02,
        -7.1280e-02,  2.2862e-02, -1.6270e-03,  3.0814e-02, -5.3162e-02,
         4.8272e-04, -4.8584e-02, -5.6914e-03,  4.9828e-03,  2.7363e-03,
        -9.3555e-03, -6.6842e-03,  2.3536e-02, -7.8033e-03,  1.8281e-02,
         1.2923e-02, -5.7661e-02, -2.2203e-02,  4.0490e-03, -2.0545e-02,
        -2.7185e-02, -1.5683e-02, -2.2524e-03,  1.0900e-02,  1.3682e-02,
        -8.1649e-02,  3.0798e-02, -1.8479e-02,  1.8500e-02,  1.4674e-02,
        -1.4161e-02, -3.4882e-02, -8.3396e-03,  2.7488e-02, -2.6695e-02,
        -2.9426e-02, -2.2590e-03,  5.9207e-02,  1.8346e-02,  2.6968e-02,
        -1.9969e-02, -2.8826e-02,  9.5878e-03,  4.1633e-02,  3.6531e-03,
        -2.8570e-02, -1.9249e-02,  1.2564e-02,  2.4293e-02,  2.4954e-02,
        -2.8459e-02, -1.0892e-02, -9.8302e-03, -1.2400e-02,  1.0530e-02,
         4.8705e-02,  1.9814e-02, -3.6498e-02, -8.0256e-02,  6.8143e-03,
        -1.1835e-02, -5.4331e-03,  6.8044e-02,  5.7409e-03,  1.7877e-02,
        -5.9596e-02,  5.0728e-03, -2.4227e-02,  4.8021e-02, -3.2459e-02,
         1.4161e-02, -1.6408e-02, -3.8627e-02,  7.0892e-02, -9.9767e-02,
         3.6472e-02,  3.3258e-02,  4.0078e-02,  8.3533e-02,  2.1727e-02,
        -1.5223e-02,  2.9046e-02, -9.0923e-03, -1.9629e-02,  1.7205e-02,
         1.5962e-02,  2.4136e-02, -1.5996e-02, -9.2654e-03, -1.5507e-02,
         1.3965e-02,  2.3243e-02, -4.3993e-03, -1.0413e-02,  2.2927e-02,
         2.3947e-02,  4.3216e-02,  3.8581e-02,  3.6864e-02, -6.3318e-02,
         1.7074e-02, -1.5699e-02,  5.2457e-02,  3.0043e-02, -1.7733e-02,
         2.7404e-02,  2.0246e-02, -1.6243e-02,  1.8136e-02,  1.5107e-02,
        -2.4182e-02, -1.3113e-02, -4.0250e-02,  6.7131e-03, -6.6268e-03,
         3.6066e-02, -1.5631e-02, -8.6614e-03, -6.7868e-03, -1.3511e-02,
        -7.4573e-03,  4.9593e-02, -3.2400e-02, -1.7471e-02, -4.5686e-03,
        -7.8281e-05, -2.2296e-02,  8.1223e-04, -3.4111e-03, -6.9632e-02,
        -7.5439e-03, -3.1384e-02,  8.9004e-03,  1.6888e-02,  2.5107e-02,
         1.9451e-02, -2.9510e-02, -4.1659e-02, -4.5345e-03, -2.3955e-03,
         3.4199e-02, -4.2084e-02,  1.5062e-02, -2.1123e-02,  3.9235e-02,
         8.0206e-02, -3.6787e-02, -6.8280e-03,  2.0849e-02, -1.4635e-02,
        -3.0734e-02,  5.2872e-02, -1.1676e-02, -8.1689e-03, -1.8677e-02,
        -4.8922e-03, -1.2036e-02,  5.6483e-02,  3.5672e-02,  3.1204e-02,
        -2.1356e-02,  7.1243e-03, -2.7085e-02,  2.7719e-02,  4.7473e-02,
        -6.0322e-02, -4.4163e-02, -4.0432e-04, -1.7918e-02,  2.8354e-02,
        -6.6233e-02,  1.5936e-02,  3.5317e-02, -4.6953e-03, -6.0799e-02,
        -4.3433e-02,  1.9848e-02,  2.2587e-02, -4.5570e-02, -9.5904e-03,
        -1.9921e-02,  1.4142e-02,  3.6231e-02,  2.0156e-02, -1.1794e-02,
         2.1933e-02, -2.2644e-02, -1.8755e-02, -2.4745e-02,  3.7587e-02,
        -6.5807e-03,  7.5497e-03, -6.2124e-02, -3.3643e-03,  6.0679e-03,
        -6.8466e-02, -7.0809e-02, -3.6040e-03,  3.8396e-02,  1.2153e-02,
         2.0132e-02,  3.5183e-02, -2.6021e-02,  1.0438e-02, -1.5540e-02,
         5.0649e-02,  1.7937e-02, -8.4167e-04, -5.9040e-02, -2.8252e-02,
         6.2257e-03,  3.5424e-02, -5.9716e-03, -8.7228e-03, -6.7746e-03,
         1.1410e-02, -9.6905e-02, -3.8541e-02, -4.1136e-02,  6.7404e-02,
         2.1019e-02,  1.2564e-02, -1.3213e-02,  5.0434e-02,  3.7955e-02,
        -2.4641e-02,  7.8758e-03,  9.0562e-04,  2.7685e-02,  2.2655e-02,
         3.7123e-02, -4.0116e-02, -2.1802e-02,  9.6987e-02,  1.6395e-02,
         2.1965e-02, -3.0092e-03, -3.4674e-02, -1.4551e-02,  4.1678e-03,
        -5.4413e-02,  3.6432e-05,  3.7270e-02, -6.2399e-02,  6.4965e-02,
         5.8701e-02, -3.2393e-02,  8.7459e-02,  9.0186e-02,  4.6961e-02,
        -4.7825e-02, -7.0662e-02, -5.4395e-02,  2.7740e-02, -6.1380e-03,
        -3.5223e-02,  1.1597e-02, -4.2838e-02,  4.6039e-03,  6.9813e-02,
        -8.1786e-02, -5.5221e-03, -1.1091e-01,  1.6300e-02,  8.5980e-02,
         6.7587e-02,  7.2574e-04,  4.0584e-03, -1.8969e-02, -2.9779e-03,
         8.4728e-03,  6.0386e-02, -1.6579e-02,  3.2149e-02, -1.7186e-03,
         6.0060e-03, -2.7908e-02, -7.8481e-02, -1.8576e-02,  1.5275e-02,
        -2.1066e-02, -4.0799e-02,  6.8687e-02,  2.0633e-02, -4.0296e-02,
         7.5547e-04,  8.2728e-03, -4.1280e-02,  4.6019e-02,  4.6086e-02,
         3.3949e-02, -1.1119e-02, -4.9492e-02,  4.2305e-02,  8.4000e-03,
         1.4146e-02,  3.5396e-02,  3.9418e-02, -1.6859e-02,  1.9787e-02,
         1.0656e-02,  1.4325e-02,  4.8720e-02, -4.6713e-03, -4.0716e-02,
         1.5703e-02, -4.0247e-02, -3.7498e-02, -3.2018e-03,  6.1261e-02,
        -1.9541e-02, -1.1717e-02, -3.0932e-02, -6.8161e-03, -3.6450e-02,
         2.9689e-02, -2.2570e-02, -1.1978e-02,  4.2329e-02,  5.3808e-02,
        -2.4918e-02,  4.4623e-02, -5.4590e-03, -4.2305e-03,  3.0771e-02,
         2.4682e-02,  1.7573e-03,  4.2483e-02, -3.8642e-02,  1.3494e-02,
         1.8162e-02,  8.3127e-03, -5.9191e-02, -7.1587e-02, -3.2794e-02,
        -3.5429e-03, -7.6908e-02, -4.9656e-04, -3.8307e-02,  3.9689e-02,
         5.6057e-03, -1.0650e-02,  4.4828e-02,  1.6977e-02,  3.5325e-02,
         7.9425e-02, -4.6227e-02, -4.4668e-02, -4.4740e-02, -3.9255e-02,
        -4.0305e-02,  6.4711e-02,  1.3473e-02, -6.4377e-02,  2.6462e-02,
        -1.8546e-02, -4.1501e-02, -1.6646e-02,  6.6780e-03,  6.1870e-02,
        -4.4090e-04,  1.0790e-02, -1.9002e-02, -7.2088e-02, -3.5528e-02,
        -8.6343e-03, -6.2220e-02, -1.8995e-02,  1.5508e-02,  6.8691e-03,
         1.7205e-02, -4.8336e-02,  2.3358e-03,  1.5474e-02, -8.6179e-03,
         5.3116e-02, -2.8614e-02,  5.5935e-04,  6.1413e-02,  1.4932e-02,
         8.6209e-03, -2.1578e-02,  3.3237e-02, -8.9931e-02,  3.7740e-03,
        -6.1156e-02,  3.4964e-02, -2.7469e-02, -1.8132e-02, -7.4007e-03,
         3.3991e-02, -1.0060e-02,  6.2169e-03, -1.1681e-02, -2.9673e-02,
         1.4772e-03, -3.3162e-03,  2.3156e-02,  3.7935e-02,  2.5540e-02,
         2.5873e-02, -8.9826e-03, -3.0313e-03, -6.5431e-02, -1.6828e-02,
        -5.2621e-03, -5.7143e-02,  3.8764e-02, -1.6915e-02, -2.8886e-02,
         6.2278e-03,  6.0100e-02, -1.6510e-02,  7.3824e-02,  3.8856e-02,
        -3.7126e-02, -1.8645e-02, -3.2339e-02,  3.6972e-02,  2.5219e-02,
         1.1575e-02, -2.8572e-02,  4.5577e-02, -8.9341e-02, -5.7422e-03,
         3.7954e-02, -1.8076e-03, -1.2057e-02,  5.6094e-02, -8.1337e-03,
         2.2392e-02, -3.0197e-02,  9.9064e-02,  7.2788e-03, -9.1089e-03,
        -1.8972e-02,  5.6376e-02, -1.5387e-02,  2.7011e-02, -5.5780e-03,
         3.6654e-02,  2.0353e-03, -2.9571e-02,  3.2913e-02, -2.0319e-02,
         1.2015e-02, -6.2686e-03,  2.8275e-02,  3.3354e-02, -4.5427e-03,
        -5.9381e-03,  6.1999e-02,  1.2692e-02,  2.0015e-02, -1.6003e-02,
        -4.7410e-33, -3.0390e-02, -3.7232e-02,  3.3379e-02, -8.1769e-03,
        -9.8547e-03, -4.7184e-02, -2.4688e-02, -9.3945e-03, -3.7861e-02,
        -4.9821e-02, -3.3019e-02,  1.0378e-02,  8.3392e-03, -6.2363e-02,
         6.9884e-03, -4.6253e-02, -4.2909e-03,  4.3567e-02,  2.9196e-02,
         2.7524e-03, -4.1487e-02,  1.4581e-02,  5.6432e-02, -1.7856e-02,
         5.1964e-02, -1.5264e-02, -4.7005e-02, -4.7140e-03, -5.6717e-02,
         2.4571e-02, -2.4979e-02, -2.0909e-02,  1.7253e-02, -1.3897e-02,
        -9.2991e-03,  1.7242e-02, -4.3930e-02,  4.8677e-04, -1.8688e-02,
         4.2132e-03,  2.4748e-02, -7.9515e-03,  1.7942e-03, -1.5389e-02,
        -5.2880e-02, -2.4393e-02, -3.6665e-02, -1.0282e-02, -4.8426e-02,
         2.3205e-02, -1.3128e-02, -1.6195e-02, -1.1040e-02,  3.8452e-02,
         6.5516e-03, -5.0447e-02,  5.3727e-02, -4.0427e-02, -4.5840e-02,
         4.7044e-02,  7.1243e-02,  6.3954e-03,  1.1035e-02, -4.1953e-02,
         2.8744e-02, -3.7164e-02, -5.8515e-03, -6.4189e-02,  1.1367e-02,
         1.4936e-02,  1.8191e-02, -5.7020e-03, -9.4744e-02,  6.0482e-02,
         8.0090e-02, -6.3762e-02, -5.4337e-02,  4.0119e-02,  3.4777e-02,
         1.1039e-01,  2.9927e-02,  3.5919e-02, -4.3845e-02, -4.0503e-02,
         2.7744e-02, -1.3548e-02, -1.1480e-02, -3.4337e-03,  6.1653e-03,
         1.6632e-03,  4.3045e-02, -2.0446e-02,  2.6675e-02, -2.4364e-04,
         2.5010e-02,  6.0508e-02, -5.9889e-02,  1.2876e-02,  2.5043e-02,
         7.6875e-03, -2.1598e-02, -5.8811e-02,  3.1068e-02,  1.5914e-02,
        -2.6703e-05,  1.1671e-02,  2.0095e-02,  2.3377e-02,  6.5956e-03,
        -6.2743e-03, -8.0272e-03, -7.4746e-03, -2.2208e-02,  5.8141e-03,
        -1.2945e-02,  1.1528e-02, -2.0556e-03, -5.9155e-02,  1.8261e-02,
        -7.8628e-03,  3.2085e-02, -2.3814e-02,  6.0033e-02,  6.3661e-03,
        -1.7048e-02,  2.4001e-02,  3.9311e-02,  2.6969e-02,  1.1666e-02,
         2.7849e-03, -6.9226e-03,  4.0887e-02,  2.1403e-07,  1.6341e-02,
         1.1748e-02, -1.4490e-02, -3.2460e-02, -2.1287e-02, -1.2244e-03,
        -7.4142e-03,  1.1192e-02,  1.1824e-02,  4.0434e-02,  6.4430e-03,
         1.4626e-02,  4.9257e-03, -1.1661e-02, -8.2551e-02, -3.3044e-02,
         7.0103e-02, -2.0122e-02,  3.5608e-02,  4.6513e-02,  2.7540e-02,
        -2.5867e-02,  4.5432e-03, -1.3541e-03,  5.0872e-02, -8.3417e-03,
        -1.4239e-02, -3.3427e-02, -7.9988e-02,  3.3491e-03,  1.5812e-02,
         3.9457e-02,  7.7508e-03, -1.5638e-02,  4.6758e-02, -2.3250e-02,
         3.7940e-02,  7.0319e-02,  1.7179e-02,  9.6964e-02, -5.3829e-02,
        -8.1765e-02,  2.8256e-02, -6.3493e-02,  1.3071e-02,  1.2788e-01,
        -3.0567e-02, -4.1073e-02,  4.7219e-02,  2.5648e-02,  1.9390e-02,
        -3.0697e-03,  1.0565e-02, -8.8580e-02,  3.0044e-02, -4.1869e-02,
        -4.1464e-04, -1.8252e-02, -1.8990e-02,  1.7824e-02,  3.0981e-02,
        -2.4953e-02,  4.4105e-03,  1.0550e-01,  2.2919e-02, -7.0378e-02,
         6.7839e-02,  1.8947e-34,  3.8917e-02, -3.7148e-02,  4.6767e-02,
        -2.9321e-02, -1.6572e-03,  1.6797e-04, -5.7550e-02, -5.6358e-02,
         3.4711e-02, -7.4967e-02,  1.3048e-02], device='cuda:0')

In [31]:
#Saving embedding to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(save_path, index=False)

In [32]:
# Import saved file and view
text_chunks_and_embeddings_df_load = pd.read_csv(save_path)
text_chunks_and_embeddings_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-41,"1 THE PENAL CODE, 1860 (ACT NO.XLV OF 1860). ...",1289,279,322.25,[ 4.07653823e-02 -6.92013055e-02 2.38808561e-...
1,-41,(3) [Omitted by section 3 and 2nd Schedule of ...,545,92,136.25,[ 4.89617810e-02 -5.62559925e-02 3.61934397e-...
2,-40,"(b) B, a European British subject, commits a m...",1251,240,312.75,[ 3.32908295e-02 -5.96009120e-02 2.72631161e-...
3,-40,"Illustrations (a) The sections in this Code,...",1196,248,299.00,[ 3.59783992e-02 -5.08492589e-02 2.00839378e-...
4,-39,“Person” 11.The word “person” includes any C...,628,143,157.00,[ 3.67720313e-02 -2.46235430e-02 3.37098632e-...

# RAG - Search and Answer

### Similarity search
Similarity search or semantic search or vector search is the idea of searching on *semantic*.

With keyword search, you are trying to match the string "apple" with the string "apple".

Whereas with similarity/semantic search, you may want to search "macronutrients functions".
And get back results that don't necessarily contain the words "macronutrients functions" but get back pieces of text that match that meaning.

In [33]:
import torch
import numpy as np
device = "cuda" if torch.cuda.is_available() else "cpu"

text_chunks_and_embedding_df = pd.read_csv(save_path)
#convert embedding to array (it got converted to string when it saved)
text_chunks_and_embedding_df["embedding"] = text_chunks_and_embedding_df["embedding"].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

#converting embedding into torch tensor
embeddings = torch.tensor(np.stack(text_chunks_and_embedding_df["embedding"].tolist(), axis=0), dtype=torch.float32).to(device)
# Convert texts and embedding df to list of dicts
pages_and_chunks = text = text_chunks_and_embedding_df.to_dict(orient="records")

text_chunks_and_embeddings_df

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-41,"1 THE PENAL CODE, 1860 (ACT NO.XLV OF 1860). ...",1289,279,322.25,"[0.040765382, -0.069201306, 0.023880856, -0.05..."
1,-41,(3) [Omitted by section 3 and 2nd Schedule of ...,545,92,136.25,"[0.04896178, -0.056255993, 0.003619344, -0.024..."
2,-40,"(b) B, a European British subject, commits a m...",1251,240,312.75,"[0.03329083, -0.059600912, 0.027263116, -0.020..."
3,-40,"Illustrations (a) The sections in this Code,...",1196,248,299.00,"[0.0359784, -0.05084926, 0.020083938, -0.00351..."
4,-39,“Person” 11.The word “person” includes any C...,628,143,157.00,"[0.03677203, -0.024623543, 0.0033709863, 0.015..."
5,-39,[Repealed] 16. [Repealed by the Government o...,1119,225,279.75,"[0.043088928, -0.011165836, 0.006733916, -0.01..."
6,-39,(c) [Repealed by the Federal Laws (Revision an...,237,43,59.25,"[0.030149743, -0.054981977, 0.039542355, 0.001..."
7,-38,"“Court of justice” 20.The words ""Court of Ju...",2934,521,733.50,"[0.066430435, -0.053875513, 0.02053645, 0.0006..."
8,-37,A Municipal Commissioner is a public servant. ...,1602,302,400.50,"[0.00032928947, 0.052225422, 0.042397227, 0.08..."
9,-37,Losing wrongfully A person is said to gain w...,778,164,194.50,"[-0.019034104, 0.06002082, 0.009006251, 0.0687..."
10,-36,"Property in possession of wife, clerk or serva...",1561,289,390.25,"[0.015090436, 0.0024476273, 0.01253116, 0.0607..."
11,-36,Illustrations A writing expressing the terms...,978,182,244.50,"[0.017028587, -0.046930436, 0.025407843, 0.031..."
12,-35,the signature. “Valuable security” ...,905,192,226.25,"[-0.0018732202, -0.024646398, 0.038498204, 0.0..."
13,-35,"The word ""act"" denotes as well a series of act...",1538,326,384.50,"[0.029176613, 0.012163552, 0.009016882, 0.0143..."
14,-34,offence singly or jointly with any other perso...,1204,224,301.00,"[0.048733573, 0.013079148, 0.03582248, 0.00221..."
15,-34,"B, without collusion or co-operation with A, i...",1311,261,327.75,"[0.017417707, 0.018590372, 0.048054717, -0.028..."
16,-34,"Here, A may not have intended to cause death, ...",533,111,133.25,"[0.013659239, -0.022229318, 0.017384904, -0.03..."
17,-33,"222, 223, 224, 225, 327, 328, 329, 330, 331, 3...",1106,238,276.50,"[0.012519497, -0.05525095, 0.019827843, -0.028..."
18,-33,"“Life” 45.The word ""life"" denotes the life o...",642,153,160.50,"[0.071988866, -0.0021848725, 0.0020172212, -0...."
19,-33,"“Section” 50.The word ""section"" denotes one ...",406,83,101.50,"[0.009576073, -0.033398904, 0.029592726, 0.003..."
20,-32,“Good faith” 52.Nothing is said to be done o...,1989,388,497.25,"[-0.04667236, -0.032364924, 0.063567735, 0.035..."
21,-32,"Whoever is a member of an unlawful assembly, s...",530,102,132.50,"[-0.030500354, -0.05561532, 0.060493063, 0.020..."
22,-31,"Joining or continuing in unlawful assembly, kn...",1586,315,396.50,"[-0.0013462779, -0.069961, 0.043788888, -0.006..."
23,-31,"Hiring, or conniving at hiring, of persons to ...",1477,270,369.25,"[-0.015759083, 0.021477506, 0.050973702, 0.014..."
24,-30,"suppressing riot, etc attempts to use criminal...",2783,498,695.75,"[0.03180879, -0.016379446, 0.00937113, 0.01399..."
25,-29,Punishment for undue influence or personation ...,3076,583,769.00,"[0.015026373, 0.013343487, 0.02737753, 0.02781..."
26,-28,"servant by such bidding, shall be punished wit...",2863,518,715.75,"[0.027710875, -0.018256625, 0.02686329, -0.002..."
27,-28,"A knowingly disobeys the order, and thereby ca...",602,109,150.50,"[-0.026693841, -0.012322592, 0.02822266, 0.038..."
28,-27,CHAPTER XI OF FALSE EVIDENCE AND OFFENCES AGA...,3303,606,825.75,"[0.010263785, -0.064105965, 0.042966347, -0.02..."
29,-26,CHAPTER XIII OF OFFENCES RELATING TO WEIGHTS ...,2007,393,501.75,"[-0.031352744, 0.00023903816, 0.040711764, 0.0..."
30,-26,Malignant act likely to spread infection of di...,992,188,248.00,"[0.018919656, 0.017765412, 0.035293315, -0.082..."
31,-25,or drink intended for sale noxious as food or ...,2448,481,612.00,"[0.035417084, 0.035119705, 0.028660405, -0.036..."
32,-25,Whoever commits a public nuisance in any case ...,770,143,192.50,"[0.031044828, 0.03162071, 0.015788639, -0.0058..."
33,-24,"has in his possession any obscene book, pamphl...",2878,539,719.50,"[0.029981192, 0.052732103, 0.0148417, 0.012813..."
34,-23,"Offering of prize in connection with trade, et...",3366,620,841.50,"[0.027939716, 0.02073517, -0.0022436918, 0.062..."
35,-22,Of Criminal Force and Assault Punishment for ...,2328,426,582.00,"[0.05936711, -0.044932988, 0.0358079, -0.03578..."
36,-22,Assault or criminal force in attempt to commit...,717,134,179.25,"[0.033786006, -0.08460529, 0.024590805, 0.0085..."
37,-21,Assault or criminal force on grave provocation...,933,166,233.25,"[0.08014708, -0.053772163, 0.01031268, -0.0026..."

In [34]:
embeddings.shape

torch.Size([38, 768])

Retrival is done by following steps:
1. Define a query string.
2. Turn the query string in an embedding with same model we used to embed our text chunks.
3. Perform a [dot product](https://pytorch.org/docs/stable/generated/torch.dot.html) or [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity) function between the text embeddings and the query embedding to get similarity scores.
4. Sort the results from step 3 in descending order (a higher score means more similarity in the eyes of the model) and use these values to inspect the texts.

In [35]:
from sentence_transformers import util

query = "macronutrients functions"
print(f"Query : {query}")

query_embedding = embedding_model.encode(query, convert_to_tensor=True).to("cuda")

dot_scores = util.dot_score(query_embedding, embeddings)[0]

top_results = torch.topk(dot_scores, k=5)
top_results

Query : macronutrients functions

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

torch.return_types.topk(
values=tensor([0.0886, 0.0865, 0.0830, 0.0767, 0.0709], device='cuda:0'),
indices=tensor([31, 19, 14,  7,  4], device='cuda:0'))

In [36]:
for score, idx in zip(top_results[0], top_results[1]):
    print(f"Score: {score:.4f}")
    print("Text")
    print(pages_and_chunks[idx]["sentence_chunk"])
    print("\n\n")

Score: 0.0886
Text
or drink intended for sale noxious as food or drink, intending to sell such article as food or drink, or knowing it to be likely that the same will be sold as food or drink, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of noxious food or drink   273.Whoever sells, or offers or exposes for sale, as food or drink, any article which has been rendered or has become noxious, or is in a state unfit for food or drink, knowing or having reason to believe that the same is noxious as food or drink, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Adulteration of drugs   274.Whoever adulterates any drug or medical preparation in such a manner as to lessen the efficacy or change the operation of such drug or medical preparation, or to make it noxious, intending that it shall be sold or used for, or knowing it to be likely that it will be sold or used for, any medicinal purpose, as if it had not undergone such adulteration, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of adulterated drugs   275.Whoever, knowing any drug or medical preparation to have been adulterated in such a manner as to lessen its efficacy, to change its operation, or to render it noxious, sells the same, or offers or exposes it for sale, or issues it from any dispensary for medicinal purposes as unadulterated, or causes it to be used for medicinal purposes by any person not knowing of the adulteration, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of drug as a different drug or preparation   276.Whoever knowingly sells, or offers or exposes for sale, or issues from a dispensary for medicinal purposes, any drug or medicinal preparation, as a different drug or medical preparation, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.  Punishment for public nuisance in cases not otherwise provided for   290.



Score: 0.0865
Text
“Section”   50.The word "section" denotes one of those portions of a chapter of this Code which are distinguished by prefixed numeral figures.            “Oath”   51.The word "oath" includes a solemn affirmation substituted by law for an oath, and any declaration required or authorized by law to be made before a public servant or to be used for the purpose of proof, whether in a Court of Justice or not.



Score: 0.0830
Text
offence singly or jointly with any other person, commits that offence. Illustrations   (a) A and B agree to murder Z by severally and at different times giving him small doses of poison.A and B administer the poison according to the agreement with intent to murder Z. Z dies from the effects of the several doses of poison so administered to him.Here A and B intentionally co-operate in the commission of murder and as each of them does an act by which the death is caused, they are both guilty of the offence though their acts are separate.  (b) A and B are joint jailors, and as such, have the charge of Z, a prisoner, alternately for six hours at a time.A and B, intending to cause Z's death, knowingly co-operate in causing that effect by illegally omitting, each during the time of his attendance, to furnish Z with food supplied to them for that purpose.Z dies of hunger.Both A and B are guilty of the murder of Z.  (c) A, a jailor, has the charge of Z, a prisoner.A intending to cause Z's death, illegally omits to supply Z with food; in consequence of which Z is much reduced in strength, but the starvation is not sufficient to cause his death.A is dismissed from his office, and B succeeds him.



Score: 0.0767
Text
“Court of justice”   20.The words "Court of Justice" denote a Judge who is empowered by law to act judicially alone, or a body of Judges which is empowered by law to act judicially as a body, when such Judge or body of Judges is acting judicially.            “Public servant”   21.The words "public servant" denote a person falling under any of the descriptions hereinafter following, namely:-  First.-[Omitted by section 2 of the Penal Code (Amendment) Ordinance, 1982 (Ordinance No.X of 1982)];  Second.Every Commissioned Officer in the Military, Naval or Air Forces of Bangladesh 10[ * * *];  11[ Third.- Every Judge including any person empowered by any law to perform, whether by himself or as a member of any body of persons, any adjudicatory function;]  Fourth.- very officer of a Court of Justice whose duty it is, as such officer, to investigate or report on any matter of law or fact, or to make, authenticate, or keep any document, or to take charge or dispose of any property, or to execute any judicial process, or to administer any oath, or to interpret, or to preserve order in the Court; and every person specially authorized by a Court of Justice to perform any of such duties;  Fifth.-Every juryman, assessor, or member of a panchayat assisting a Court of Justice or public servant;  Sixth.-Every arbitrator or other person to whom any cause or matter has been referred for decision or report by any Court of Justice, or by any other competent public authority;  Seventh.-Every person who holds any office by virtue of which he is empowered to place or keep any person in confinement;  Eighth.-Every officer of the Government whose duty it is, as such officer, to prevent offences, to give information of offences, to bring offenders to justice, or to protect the public health, safety or convenience;  Ninth.-Every officer whose duty it is, such officer, to take, receive, keep or expend any property on behalf of the Government, or to make any survey, assessment or contract on behalf of the Government, or to execute any revenue-process, or to investigate, or to report, on any matter affecting the pecuniary interests of the Government, or to make, authenticate or keep any document relating to the pecuniary interest of the Government, or to prevent the infraction of any law for the protection of the pecuniary interests of the Government 12[ * * *];  Tenth.-Every officer whose duty it is, as such officer, to take, receive, keep or expend any property, to make any survey or assessment or to levy any rate or tax for any secular common purpose of any village, town or district, or to make, authenticate or keep any document for the ascertaining of the rights of the people of any village, town or district;  Eleventh.-Every person who holds any office in virtue of which he is empowered to prepare, publish, maintain or revise an electoral roll or to conduct an election or part of an election.  Illustration



Score: 0.0709
Text
“Person”   11.The word “person” includes any Company or Association, or body of persons, whether incorporated or not.            “Public”   12.The word “public” includes any class of the public or any community.            [Omitted]   13. [Omitted by Article 2 and Schedule of the Central Laws (Adaptation) Order, 1961.]            “Servant of the State”   14.The words 9[ Servant of the Republic] denote all officers or servant, continued, appointed or employed in Bangladesh by or under the authority of the Government.            [Repealed]   15. [Repealed by the Government of India (Adaptation of Indian Laws) Order, 1937.]

In [37]:
def retrieve_relevant_resources(query: str, n_resources_to_return: int=5):
    
    query_embedding = embedding_model.encode(query, convert_to_tensor=True).to("cuda")

    dot_scores = util.dot_score(query_embedding, embeddings)[0]

    scores, indices = torch.topk(dot_scores, k=n_resources_to_return)
    
    return scores, indices

In [38]:
retrieve_relevant_resources(query)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

(tensor([0.0886, 0.0865, 0.0830, 0.0767, 0.0709], device='cuda:0'),
 tensor([31, 19, 14,  7,  4], device='cuda:0'))

In [39]:
def print_top_results_and_scores(query: str, n_resources_to_return: int=5):
    """
    Takes a query, retrieves most relevant resources and prints them out in descending order.
    """
    scores, indices = retrieve_relevant_resources(query, n_resources_to_return=n_resources_to_return)
    for score, idx in zip(scores, indices):
        print(f"Score: {score:.4f}")
        print("Text")
        print(pages_and_chunks[idx]["sentence_chunk"])
        print("\n\n")

In [40]:
print_top_results_and_scores(query)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Score: 0.0886
Text
or drink intended for sale noxious as food or drink, intending to sell such article as food or drink, or knowing it to be likely that the same will be sold as food or drink, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of noxious food or drink   273.Whoever sells, or offers or exposes for sale, as food or drink, any article which has been rendered or has become noxious, or is in a state unfit for food or drink, knowing or having reason to believe that the same is noxious as food or drink, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Adulteration of drugs   274.Whoever adulterates any drug or medical preparation in such a manner as to lessen the efficacy or change the operation of such drug or medical preparation, or to make it noxious, intending that it shall be sold or used for, or knowing it to be likely that it will be sold or used for, any medicinal purpose, as if it had not undergone such adulteration, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of adulterated drugs   275.Whoever, knowing any drug or medical preparation to have been adulterated in such a manner as to lessen its efficacy, to change its operation, or to render it noxious, sells the same, or offers or exposes it for sale, or issues it from any dispensary for medicinal purposes as unadulterated, or causes it to be used for medicinal purposes by any person not knowing of the adulteration, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.            Sale of drug as a different drug or preparation   276.Whoever knowingly sells, or offers or exposes for sale, or issues from a dispensary for medicinal purposes, any drug or medicinal preparation, as a different drug or medical preparation, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand taka, or with both.  Punishment for public nuisance in cases not otherwise provided for   290.



Score: 0.0865
Text
“Section”   50.The word "section" denotes one of those portions of a chapter of this Code which are distinguished by prefixed numeral figures.            “Oath”   51.The word "oath" includes a solemn affirmation substituted by law for an oath, and any declaration required or authorized by law to be made before a public servant or to be used for the purpose of proof, whether in a Court of Justice or not.



Score: 0.0830
Text
offence singly or jointly with any other person, commits that offence. Illustrations   (a) A and B agree to murder Z by severally and at different times giving him small doses of poison.A and B administer the poison according to the agreement with intent to murder Z. Z dies from the effects of the several doses of poison so administered to him.Here A and B intentionally co-operate in the commission of murder and as each of them does an act by which the death is caused, they are both guilty of the offence though their acts are separate.  (b) A and B are joint jailors, and as such, have the charge of Z, a prisoner, alternately for six hours at a time.A and B, intending to cause Z's death, knowingly co-operate in causing that effect by illegally omitting, each during the time of his attendance, to furnish Z with food supplied to them for that purpose.Z dies of hunger.Both A and B are guilty of the murder of Z.  (c) A, a jailor, has the charge of Z, a prisoner.A intending to cause Z's death, illegally omits to supply Z with food; in consequence of which Z is much reduced in strength, but the starvation is not sufficient to cause his death.A is dismissed from his office, and B succeeds him.



Score: 0.0767
Text
“Court of justice”   20.The words "Court of Justice" denote a Judge who is empowered by law to act judicially alone, or a body of Judges which is empowered by law to act judicially as a body, when such Judge or body of Judges is acting judicially.            “Public servant”   21.The words "public servant" denote a person falling under any of the descriptions hereinafter following, namely:-  First.-[Omitted by section 2 of the Penal Code (Amendment) Ordinance, 1982 (Ordinance No.X of 1982)];  Second.Every Commissioned Officer in the Military, Naval or Air Forces of Bangladesh 10[ * * *];  11[ Third.- Every Judge including any person empowered by any law to perform, whether by himself or as a member of any body of persons, any adjudicatory function;]  Fourth.- very officer of a Court of Justice whose duty it is, as such officer, to investigate or report on any matter of law or fact, or to make, authenticate, or keep any document, or to take charge or dispose of any property, or to execute any judicial process, or to administer any oath, or to interpret, or to preserve order in the Court; and every person specially authorized by a Court of Justice to perform any of such duties;  Fifth.-Every juryman, assessor, or member of a panchayat assisting a Court of Justice or public servant;  Sixth.-Every arbitrator or other person to whom any cause or matter has been referred for decision or report by any Court of Justice, or by any other competent public authority;  Seventh.-Every person who holds any office by virtue of which he is empowered to place or keep any person in confinement;  Eighth.-Every officer of the Government whose duty it is, as such officer, to prevent offences, to give information of offences, to bring offenders to justice, or to protect the public health, safety or convenience;  Ninth.-Every officer whose duty it is, such officer, to take, receive, keep or expend any property on behalf of the Government, or to make any survey, assessment or contract on behalf of the Government, or to execute any revenue-process, or to investigate, or to report, on any matter affecting the pecuniary interests of the Government, or to make, authenticate or keep any document relating to the pecuniary interest of the Government, or to prevent the infraction of any law for the protection of the pecuniary interests of the Government 12[ * * *];  Tenth.-Every officer whose duty it is, as such officer, to take, receive, keep or expend any property, to make any survey or assessment or to levy any rate or tax for any secular common purpose of any village, town or district, or to make, authenticate or keep any document for the ascertaining of the rights of the people of any village, town or district;  Eleventh.-Every person who holds any office in virtue of which he is empowered to prepare, publish, maintain or revise an electoral roll or to conduct an election or part of an election.  Illustration



Score: 0.0709
Text
“Person”   11.The word “person” includes any Company or Association, or body of persons, whether incorporated or not.            “Public”   12.The word “public” includes any class of the public or any community.            [Omitted]   13. [Omitted by Article 2 and Schedule of the Central Laws (Adaptation) Order, 1961.]            “Servant of the State”   14.The words 9[ Servant of the Republic] denote all officers or servant, continued, appointed or employed in Bangladesh by or under the authority of the Government.            [Repealed]   15. [Repealed by the Government of India (Adaptation of Indian Laws) Order, 1937.]

# Installing Gemma-2b
We will be using Gemma_instruct_2b for this.

In [41]:
!pip install -q -U keras-nlp
!pip install -q -U keras>=3

import os

os.environ["KERAS_BACKEND"] = "jax"  # Or "torch" or "tensorflow".
# Avoid memory fragmentation on JAX backend.
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]="1.00"

/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [42]:
import keras
import keras_nlp
gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma_instruct_2b_en")

normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.

In [43]:
input_text = "Is it legal for a person under the age of 9 to be held criminally liable according to penal code?use reference"

outputs = gemma_lm.generate(input_text, max_length=100)
print(outputs)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1733119504.743222      30 service.cc:145] XLA service 0x5c6a587d8ed0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1733119504.743296      30 service.cc:153]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
I0000 00:00:1733119511.353147      30 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Is it legal for a person under the age of 9 to be held criminally liable according to penal code?use reference to relevant legal sources.

Sure, here's the answer to your question:

Whether a person under the age of 9 can be held criminally liable under the penal code depends on several factors, including the specific jurisdiction's laws and the nature of the charge.

**Relevant Legal Sources:**

* **Juvenile Delinquency Act (JDA)**

In [44]:
input_text = "is it illegal to drive without driving licsence,accourding to the penal code 1860?use artical, if you dont find it say no"

outputs = gemma_lm.generate(input_text, max_length=500)
print(outputs)

is it illegal to drive without driving licsence,accourding to the penal code 1860?use artical, if you dont find it say no.

Sure, here's the answer:

No, the penal code 1860 does not prohibit driving without a driver's license.

In [45]:
input_text = "Is it legal for a person to act in self-defense if their life is threatened accourding to the penal code 1860?use referance, if you dont find it say no"

outputs = gemma_lm.generate(input_text, max_length=500)
print(outputs)

Is it legal for a person to act in self-defense if their life is threatened accourding to the penal code 1860?use referance, if you dont find it say no.

Sure, here's a summary of the relevant portion of the penal code 1860 and my answer:

**Penal Code 1860, Section 24:**

> "A person who, in reasonable fear of imminent deadly or grievous harm, uses any means to defend himself or his property, or to prevent or repel an imminent violent attack, shall not be prosecuted for the act of self-defense."

**Answer:**

No, the Penal Code 1860 does not authorize a person to act in self-defense if their life is threatened. Self-defense is only permitted when the use of deadly force is absolutely necessary and there is no other reasonable means to protect oneself from imminent deadly or grievous harm.

In [ ]:
input_text = "Is it legal for a person to act in self-defense if their life is threatened accourding to the penal code 1860?use referance, if you dont find it say no"

outputs = gemma_lm.generate(input_text, max_length=500)
print(outputs)